apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kp8il6xi2-go
  janus-idp.io/tekton: kp8il6xi2-go
  backstage.io/kubernetes-id: kp8il6xi2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kp8il6xi2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
